site_name: Meus Estudos e Projetos
site_description: Registro dos meus estudos e projetos
site_author: Marcos Vinicius

nav:
  - HOME: index.md
  - Atividades:
      - Atividade 1: atividades/atividade1.md
      - Atividade 2: atividades/atividade2.md

theme:
  name: material
  logo: assets/24c2.png
  favicon: assets/meetup-brands.svg
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue-grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: ht
    - icon: fontawesome/brands/linkedin
      link: ht
    - icon: fontawesome/solid/registered
      link: ht

plugins:
  # - swagger-ui-tag
  - search
  - mkdocs-pdf
  # - pdf-export
